#!/usr/bin/env bash

set -eu

[ -z "$CIRCLE_USERNAME" ] && { echo "Must be run on CircleCI."; exit 1;}

echo ">> Building Packages..."
python setup.py build sdist bdist bdist_dumb

echo ">> Uploading Packages to PyPi..."
twine upload dist/* -u TheOrangeOne -p $PYPI_PASSWORD
